DEBUG = True

USERNAME = ''
PASSWORD = ''
SERVER = 'localhost'
DB = 'videos'

SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'
SQLALCHEMY_TRACK_MODIFICATIONS = True


